apiVersion: v1
kind: Pod
metadata:
  name: nginix
  labels:
    name: nginix
    env: production
spec:
  containers:
  - name: nginix
    image: nginix
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
